##########################################################################################################
####################### START OF PYUIC5 Generated Python Code#############################################
##########################################################################################################
from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(676, 600)
        MainWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.export_dir = QtWidgets.QLineEdit(self.centralwidget)
        self.export_dir.setGeometry(QtCore.QRect(10, 40, 591, 20))
        self.export_dir.setObjectName("export_dir")
        self.export_dir_pb = QtWidgets.QPushButton(self.centralwidget)
        self.export_dir_pb.setGeometry(QtCore.QRect(610, 40, 51, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.export_dir_pb.setFont(font)
        self.export_dir_pb.setObjectName("export_dir_pb")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 210, 631, 341))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 629, 339))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.output_terminal = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.output_terminal.setGeometry(QtCore.QRect(10, 10, 601, 321))
        self.output_terminal.setObjectName("output_terminal")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 180, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.run_parse_button = QtWidgets.QPushButton(self.centralwidget)
        self.run_parse_button.setGeometry(QtCore.QRect(30, 130, 71, 31))
        self.run_parse_button.setDefault(False)
        self.run_parse_button.setFlat(False)
        self.run_parse_button.setObjectName("run_parse_button")
        self.obj_id_prefix = QtWidgets.QLineEdit(self.centralwidget)
        self.obj_id_prefix.setGeometry(QtCore.QRect(10, 100, 121, 20))
        self.obj_id_prefix.setObjectName("obj_id_prefix")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.sqlDialog_Open_pb = QtWidgets.QPushButton(self.centralwidget)
        self.sqlDialog_Open_pb.setGeometry(QtCore.QRect(350, 110, 71, 31))
        self.sqlDialog_Open_pb.setObjectName("sqlDialog_Open_pb")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 676, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionHelp)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.export_dir_pb.setStatusTip(_translate("MainWindow", "Set the export source directory."))
        self.export_dir_pb.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "Set export directory:"))
        self.label_2.setText(_translate("MainWindow", "Output Terminal:"))
        self.run_parse_button.setToolTip(_translate("MainWindow", "Run the Parser"))
        self.run_parse_button.setText(_translate("MainWindow", "PARSE FILE"))
        self.run_parse_button.setShortcut(_translate("MainWindow", "Ctrl+Alt+R"))
        self.label_3.setText(_translate("MainWindow", "Object ID Prefix:"))
        self.sqlDialog_Open_pb.setText(_translate("MainWindow", "SQL Dialog"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Save output file"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionHelp.setStatusTip(_translate("MainWindow", "Run this for help on tool\'s functions."))
        self.actionHelp.setShortcut(_translate("MainWindow", "Ctrl+Shift+H"))

