##########################################################################################################
####################### START OF PYUIC5 Generated Python Code#############################################
##########################################################################################################
from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_SQLDialog(object):
    def setupUi(self, SQLDialog):
        SQLDialog.setObjectName("SQLDialog")
        SQLDialog.setWindowModality(QtCore.Qt.WindowModal)
        SQLDialog.resize(447, 170)
        self.buttonBox = QtWidgets.QDialogButtonBox(SQLDialog)
        self.buttonBox.setGeometry(QtCore.QRect(120, 130, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(SQLDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 181, 111))
        self.groupBox.setObjectName("groupBox")
        self.sqlDialog_host = QtWidgets.QLineEdit(self.groupBox)
        self.sqlDialog_host.setGeometry(QtCore.QRect(50, 20, 121, 20))
        self.sqlDialog_host.setObjectName("sqlDialog_host")
        self.sqlDialog_user = QtWidgets.QLineEdit(self.groupBox)
        self.sqlDialog_user.setGeometry(QtCore.QRect(50, 40, 121, 20))
        self.sqlDialog_user.setObjectName("sqlDialog_user")
        self.sqlDialog_password = QtWidgets.QLineEdit(self.groupBox)
        self.sqlDialog_password.setGeometry(QtCore.QRect(50, 60, 121, 20))
        self.sqlDialog_password.setObjectName("sqlDialog_password")
        self.sqlDialog_DB = QtWidgets.QLineEdit(self.groupBox)
        self.sqlDialog_DB.setGeometry(QtCore.QRect(50, 80, 121, 20))
        self.sqlDialog_DB.setObjectName("sqlDialog_DB")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(0, 20, 47, 13))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(0, 40, 47, 13))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(0, 60, 51, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(0, 80, 51, 20))
        self.label_4.setObjectName("label_4")
        self.groupBox_2 = QtWidgets.QGroupBox(SQLDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(210, 10, 221, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.create_SQLdb_pb = QtWidgets.QRadioButton(self.groupBox_2)
        self.create_SQLdb_pb.setGeometry(QtCore.QRect(10, 20, 111, 17))
        self.create_SQLdb_pb.setObjectName("create_SQLdb_pb")
        self.delete_SQLdb_pb = QtWidgets.QRadioButton(self.groupBox_2)
        self.delete_SQLdb_pb.setGeometry(QtCore.QRect(10, 50, 101, 17))
        self.delete_SQLdb_pb.setObjectName("delete_SQLdb_pb")
        self.no_action_SQLdb_pb = QtWidgets.QRadioButton(self.groupBox_2)
        self.no_action_SQLdb_pb.setGeometry(QtCore.QRect(10, 80, 82, 17))
        self.no_action_SQLdb_pb.setObjectName("no_action_SQLdb_pb")
        self.sql_action_pb = QtWidgets.QPushButton(self.groupBox_2)
        self.sql_action_pb.setGeometry(QtCore.QRect(120, 30, 75, 41))
        self.sql_action_pb.setObjectName("sql_action_pb")

        self.retranslateUi(SQLDialog)
        self.buttonBox.accepted.connect(SQLDialog.accept)
        self.buttonBox.rejected.connect(SQLDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SQLDialog)

    def retranslateUi(self, SQLDialog):
        _translate = QtCore.QCoreApplication.translate
        SQLDialog.setWindowTitle(_translate("SQLDialog", "Dialog"))
        self.groupBox.setTitle(_translate("SQLDialog", "Database Settings"))
        self.label.setText(_translate("SQLDialog", "host:"))
        self.label_2.setText(_translate("SQLDialog", "user:"))
        self.label_3.setText(_translate("SQLDialog", "password:"))
        self.label_4.setText(_translate("SQLDialog", "database:"))
        self.groupBox_2.setTitle(_translate("SQLDialog", "Database Action"))
        self.create_SQLdb_pb.setText(_translate("SQLDialog", "Create Database"))
        self.delete_SQLdb_pb.setText(_translate("SQLDialog", "Delete Database"))
        self.no_action_SQLdb_pb.setText(_translate("SQLDialog", "No Action"))
        self.sql_action_pb.setText(_translate("SQLDialog", "Take Action"))